<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Mori's Personal Site</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap');
    body {
      margin: 0;
      font-family: 'Roboto', sans-serif;
      background: linear-gradient(to right, #8e2de2, #4a00e0);
      color: #fff;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      min-height: 100vh;
    }
    .card {
      background-color: #ffffff10;
      backdrop-filter: blur(10px);
      border-radius: 20px;
      padding: 40px;
      max-width: 600px;
      box-shadow: 0 8px 32px 0 rgba( 31, 38, 135, 0.37 );
      text-align: center;
    }
    h1 {
      font-size: 2.5em;
      margin-bottom: 0.3em;
    }
    p {
      font-size: 1.2em;
      line-height: 1.6em;
    }
    .btn {
      margin-top: 20px;
      padding: 10px 25px;
      font-size: 1em;
      color: #4a00e0;
      background: #fff;
      border: none;
      border-radius: 25px;
      cursor: pointer;
      text-decoration: none;
      transition: background 0.3s;
    }
    .btn:hover {
      background: #e0e0e0;
    }
  </style>
</head>
<body>
  <div class="card">
    <h1>Hello, I'm Mori!</h1>
    <p>Welcome to my personal website. I'm passionate about technology, creativity, and learning new things every day.</p>
    <p>This site is built using simple HTML and CSS, hosted for free using GitHub Pages.</p>
    <a href="https://github.com" target="_blank" class="btn">Visit My GitHub</a>
  </div>
</body>
</html>
